# Generated by Django 4.0.4 on 2022-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='gift',
        ),
    ]
