# Generated by Django 4.0.4 on 2022-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_auto_20200408_1844'),
        ('user', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(to='friendship.friend'),
        ),
    ]
