# Generated by Django 4.0.4 on 2022-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_auto_20200408_1844'),
        ('user', '0005_profile_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(to='friendship.follow'),
        ),
    ]
