# Generated by Django 4.0.4 on 2022-06-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
